#!/usr/bin/env sh
set -eu

FRONT_HOST="${FRONT_HOST:-127.0.0.1}"
FRONT_PORT="${FRONT_PORT:-8000}"
BACKEND_HOST="${BACKEND_HOST:-127.0.0.1}"
BACKEND_PORT="${BACKEND_PORT:-18000}"
LOG_DIR="${LOG_DIR:-$HOME/vllm-lazy-logs}"
SCRIPT="${SCRIPT:-$HOME/bin/ds4_vllm_lazy_proxy.py}"
WAIT="${WAIT:-1}"
GGUF_MODELS_ROOT="${GGUF_MODELS_ROOT:-$HOME/models/ds4}"
DS4_DFLASH_ROOT="${DS4_DFLASH_ROOT:-$HOME/models/hf/z-lab}"
GGUF_BACKEND="${GGUF_BACKEND:-ds4_server}"
GGUF_CTX="${GGUF_CTX:-${MAX_MODEL_LEN:-32768}}"
DS4_SERVER="${DS4_SERVER:-$HOME/src/ds4/ds4-server}"
LLAMA_SERVER="${LLAMA_SERVER:-$HOME/src/llama.cpp-kamnxt/build-cuda/bin/llama-server}"
DEEPSEEK_V4_REMOTE_BASE="${DEEPSEEK_V4_REMOTE_BASE:-http://10.10.100.14:8000}"
DEEPSEEK_V4_REMOTE_MODEL="${DEEPSEEK_V4_REMOTE_MODEL:-deepseek-v4-flash}"
DS4_REMOTE_MODELS_JSON="${DS4_REMOTE_MODELS_JSON:-}"
DS4_GATEWAY_MODELS_JSON="${DS4_GATEWAY_MODELS_JSON:-${DS4_LOCAL_MODELS_JSON:-}}"
DS4_RESIDENT_MODELS_JSON="${DS4_RESIDENT_MODELS_JSON:-}"
DS4_RESIDENT_BACKEND_BASE_PORT="${DS4_RESIDENT_BACKEND_BASE_PORT:-18100}"
DS4_RESIDENT_START="${DS4_RESIDENT_START:-1}"
MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-32768}"
MAX_NUM_SEQS="${MAX_NUM_SEQS:-64}"
GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.75}"
VLLM_ENABLE_CHUNKED_PREFILL="${VLLM_ENABLE_CHUNKED_PREFILL:-1}"
VLLM_ENABLE_PREFIX_CACHING="${VLLM_ENABLE_PREFIX_CACHING:-1}"
VLLM_ASYNC_SCHEDULING="${VLLM_ASYNC_SCHEDULING:-1}"
DS4_DFLASH_NUM_SPEC_TOKENS="${DS4_DFLASH_NUM_SPEC_TOKENS:-15}"
DS4_DFLASH_GPU_MEMORY_UTILIZATION="${DS4_DFLASH_GPU_MEMORY_UTILIZATION:-0.85}"
DS4_DFLASH_MAX_NUM_SEQS="${DS4_DFLASH_MAX_NUM_SEQS:-16}"
DS4_GATEWAY_TUNING_FILE="${DS4_GATEWAY_TUNING_FILE:-}"
DS4_GATEWAY_TUNING_JSON="${DS4_GATEWAY_TUNING_JSON:-}"
CPU_SERVICE_WORKERS="${CPU_SERVICE_WORKERS:-16}"
CPU_SERVICE_MAX_ITEMS="${CPU_SERVICE_MAX_ITEMS:-1024}"
CPU_SERVICE_MAX_CONCURRENCY="${CPU_SERVICE_MAX_CONCURRENCY:-16}"
CPU_SERVICE_DEFAULT_CONCURRENCY="${CPU_SERVICE_DEFAULT_CONCURRENCY:-4}"
CPU_SERVICE_MAX_TEXT_BYTES="${CPU_SERVICE_MAX_TEXT_BYTES:-1048576}"
CPU_SERVICE_COMMAND_TIMEOUT="${CPU_SERVICE_COMMAND_TIMEOUT:-120}"
CPU_SERVICE_COMMAND_OUTPUT_BYTES="${CPU_SERVICE_COMMAND_OUTPUT_BYTES:-65536}"
CPU_SERVICE_COMMANDS_JSON="${CPU_SERVICE_COMMANDS_JSON:-{}}"

mkdir -p "$LOG_DIR"
if [ ! -x "$SCRIPT" ]; then
	echo "missing lazy proxy script: $SCRIPT" >&2
	exit 2
fi

pid_file="$LOG_DIR/lazy-proxy-$FRONT_PORT.pid"
log_file="$LOG_DIR/lazy-proxy-$FRONT_PORT.log"

if [ -s "$pid_file" ] && kill -0 "$(cat "$pid_file")" 2>/dev/null; then
	echo "model gateway already running: pid=$(cat "$pid_file") endpoint=http://$FRONT_HOST:$FRONT_PORT/v1 log=$log_file"
else
	FRONT_HOST="$FRONT_HOST" FRONT_PORT="$FRONT_PORT" BACKEND_HOST="$BACKEND_HOST" BACKEND_PORT="$BACKEND_PORT" LOG_DIR="$LOG_DIR" \
		GGUF_MODELS_ROOT="$GGUF_MODELS_ROOT" DS4_DFLASH_ROOT="$DS4_DFLASH_ROOT" GGUF_BACKEND="$GGUF_BACKEND" GGUF_CTX="$GGUF_CTX" \
		DS4_SERVER="$DS4_SERVER" LLAMA_SERVER="$LLAMA_SERVER" DS4_GATEWAY_MODELS_JSON="$DS4_GATEWAY_MODELS_JSON" \
		DEEPSEEK_V4_REMOTE_BASE="$DEEPSEEK_V4_REMOTE_BASE" DEEPSEEK_V4_REMOTE_MODEL="$DEEPSEEK_V4_REMOTE_MODEL" \
		DS4_REMOTE_MODELS_JSON="$DS4_REMOTE_MODELS_JSON" MAX_NUM_BATCHED_TOKENS="$MAX_NUM_BATCHED_TOKENS" \
		DS4_RESIDENT_MODELS_JSON="$DS4_RESIDENT_MODELS_JSON" \
		DS4_RESIDENT_BACKEND_BASE_PORT="$DS4_RESIDENT_BACKEND_BASE_PORT" DS4_RESIDENT_START="$DS4_RESIDENT_START" \
		MAX_NUM_SEQS="$MAX_NUM_SEQS" GPU_MEMORY_UTILIZATION="$GPU_MEMORY_UTILIZATION" \
		VLLM_ENABLE_CHUNKED_PREFILL="$VLLM_ENABLE_CHUNKED_PREFILL" VLLM_ENABLE_PREFIX_CACHING="$VLLM_ENABLE_PREFIX_CACHING" \
		VLLM_ASYNC_SCHEDULING="$VLLM_ASYNC_SCHEDULING" DS4_DFLASH_NUM_SPEC_TOKENS="$DS4_DFLASH_NUM_SPEC_TOKENS" \
		DS4_DFLASH_GPU_MEMORY_UTILIZATION="$DS4_DFLASH_GPU_MEMORY_UTILIZATION" DS4_DFLASH_MAX_NUM_SEQS="$DS4_DFLASH_MAX_NUM_SEQS" \
		DS4_GATEWAY_TUNING_FILE="$DS4_GATEWAY_TUNING_FILE" \
		DS4_GATEWAY_TUNING_JSON="$DS4_GATEWAY_TUNING_JSON" CPU_SERVICE_WORKERS="$CPU_SERVICE_WORKERS" \
		CPU_SERVICE_MAX_ITEMS="$CPU_SERVICE_MAX_ITEMS" CPU_SERVICE_MAX_CONCURRENCY="$CPU_SERVICE_MAX_CONCURRENCY" \
		CPU_SERVICE_DEFAULT_CONCURRENCY="$CPU_SERVICE_DEFAULT_CONCURRENCY" CPU_SERVICE_MAX_TEXT_BYTES="$CPU_SERVICE_MAX_TEXT_BYTES" \
		CPU_SERVICE_COMMAND_TIMEOUT="$CPU_SERVICE_COMMAND_TIMEOUT" CPU_SERVICE_COMMAND_OUTPUT_BYTES="$CPU_SERVICE_COMMAND_OUTPUT_BYTES" \
		CPU_SERVICE_COMMANDS_JSON="$CPU_SERVICE_COMMANDS_JSON" \
		nohup python3 "$SCRIPT" >"$log_file" 2>&1 &
	echo "$!" >"$pid_file"
	echo "started model gateway: pid=$(cat "$pid_file") endpoint=http://$FRONT_HOST:$FRONT_PORT/v1 backend=http://$BACKEND_HOST:$BACKEND_PORT/v1 log=$log_file"
fi

if [ "$WAIT" = "1" ]; then
	i=0
	while [ "$i" -lt 60 ]; do
		if curl -fsS "http://$FRONT_HOST:$FRONT_PORT/health" >/dev/null; then
			curl -fsS "http://$FRONT_HOST:$FRONT_PORT/v1/models" | python3 -c 'import sys,json; print(len(json.load(sys.stdin)["data"]))'
			exit 0
		fi
		if ! kill -0 "$(cat "$pid_file")" 2>/dev/null; then
			echo "lazy proxy exited before readiness" >&2
			tail -120 "$log_file" >&2 || true
			exit 3
		fi
		i=$((i + 1))
		sleep 1
	done
	echo "timeout waiting for lazy proxy readiness" >&2
	tail -120 "$log_file" >&2 || true
	exit 4
fi
