#!/usr/bin/env python3

import json
import re
import sys
from argparse import ArgumentParser
from pathlib import Path
from typing import Any


TENSOR_BINDINGS = [
	("hc_head_base", "mtp.0.hc_head_base.weight"),
	("hc_head_fn", "mtp.0.hc_head_fn.weight"),
	("hc_head_scale", "mtp.0.hc_head_scale.weight"),
	("e_proj", "mtp.0.e_proj.weight"),
	("h_proj", "mtp.0.h_proj.weight"),
	("enorm", "mtp.0.enorm.weight"),
	("hnorm", "mtp.0.hnorm.weight"),
	("norm", "mtp.0.norm.weight"),
	("hc_attn_fn", "mtp.0.hc_attn_fn.weight"),
	("hc_attn_scale", "mtp.0.hc_attn_scale.weight"),
	("hc_attn_base", "mtp.0.hc_attn_base.weight"),
	("attn_norm", "mtp.0.attn_norm.weight"),
	("attn_q_a", "mtp.0.attn_q_a.weight"),
	("attn_q_a_norm", "mtp.0.attn_q_a_norm.weight"),
	("attn_q_b", "mtp.0.attn_q_b.weight"),
	("attn_kv", "mtp.0.attn_kv.weight"),
	("attn_kv_a_norm", "mtp.0.attn_kv_a_norm.weight"),
	("attn_sinks", "mtp.0.attn_sinks.weight"),
	("attn_output_a", "mtp.0.attn_output_a.weight"),
	("attn_output_b", "mtp.0.attn_output_b.weight"),
	("hc_ffn_fn", "mtp.0.hc_ffn_fn.weight"),
	("hc_ffn_scale", "mtp.0.hc_ffn_scale.weight"),
	("hc_ffn_base", "mtp.0.hc_ffn_base.weight"),
	("ffn_norm", "mtp.0.ffn_norm.weight"),
	("ffn_gate_inp", "mtp.0.ffn_gate_inp.weight"),
	("exp_probs_b_bias", "mtp.0.exp_probs_b.bias"),
	("ffn_gate_exps", "mtp.0.ffn_gate_exps.weight"),
	("ffn_up_exps", "mtp.0.ffn_up_exps.weight"),
	("ffn_down_exps", "mtp.0.ffn_down_exps.weight"),
	("ffn_gate_shexp", "mtp.0.ffn_gate_shexp.weight"),
	("ffn_up_shexp", "mtp.0.ffn_up_shexp.weight"),
	("ffn_down_shexp", "mtp.0.ffn_down_shexp.weight"),
]


GGML_TYPE_MAP = {
	"F32": "GGML_TYPE_F32",
	"F16": "GGML_TYPE_F16",
	"BF16": "GGML_TYPE_BF16",
	"Q8_0": "GGML_TYPE_Q8_0",
	"Q4_K": "GGML_TYPE_Q4_K",
	"Q6_K": "GGML_TYPE_Q6_K",
	"IQ4_NL": "GGML_TYPE_IQ4_NL",
	"IQ4_XS": "GGML_TYPE_IQ4_XS",
	"IQ3_S": "GGML_TYPE_IQ3_S",
	"IQ3_XXS": "GGML_TYPE_IQ3_XXS",
	"IQ2_XS": "GGML_TYPE_IQ2_XS",
	"IQ2_XXS": "GGML_TYPE_IQ2_XXS",
}


def die(msg: str) -> int:
	print(f"error: {msg}", file=sys.stderr)
	return 1


def load_json(path: Path) -> Any:
	with path.open("r", encoding="utf-8") as f:
		return json.load(f)


def sanitize_ident(s: str) -> str:
	s = re.sub(r"[^a-zA-Z0-9_]", "_", s)
	if re.match(r"^[0-9]", s):
		s = "_" + s
	return s


def cxx_dims_check(var: str, dims: list[int]) -> str:
	parts = [f"ggml_n_dims({var}) == {len(dims)}"]
	for i, d in enumerate(dims):
		parts.append(f"{var}->ne[{i}] == {int(d)}")
	return " && ".join(parts)


def main() -> int:
	parser = ArgumentParser()
	parser.add_argument("--sidecar-probe-json", required=True, help="Path to scripts/model_contract_probe_mtp_sidecar.py --json output.")
	parser.add_argument(
		"--namespace",
		default="ds4",
		help="C++ namespace to wrap the generated snippet (default: ds4).",
	)
	parser.add_argument(
		"--struct-name",
		default="deepseek4_mtp_sidecar",
		help="Generated C++ struct name (default: deepseek4_mtp_sidecar).",
	)
	args = parser.parse_args()

	doc = load_json(Path(args.sidecar_probe_json))
	if not isinstance(doc, dict):
		return die("sidecar-probe-json top-level is not an object")
	tensors = doc.get("tensors", None)
	if not isinstance(tensors, list):
		return die("sidecar-probe-json missing tensors[] list")

	tmap: dict[str, dict[str, Any]] = {}
	for t in tensors:
		if not isinstance(t, dict):
			continue
		name = t.get("name", None)
		if isinstance(name, str):
			tmap[name] = t

	missing = [n for _, n in TENSOR_BINDINGS if n not in tmap]
	if missing:
		return die(f"missing tensors in JSON: {missing}")

	derived_params = doc.get("derived_params", None)
	arch = doc.get("architecture", None)

	ns = sanitize_ident(str(args.namespace))
	struct_name = sanitize_ident(str(args.struct_name))

	print("// Generated by scripts/model_contract_generate_llamacpp_mtp_sidecar_binder.py")
	print("// Input: scripts/model_contract_probe_mtp_sidecar.py --json output")
	if isinstance(arch, str):
		print(f"// architecture: {arch}")
	if isinstance(derived_params, dict):
		try:
			n_embd = int(derived_params.get("n_embd", 0))
			n_head = int(derived_params.get("n_head", 0))
			n_head_dim = int(derived_params.get("n_head_dim", 0))
			n_hc = int(derived_params.get("n_hc", 0))
			n_expert = int(derived_params.get("n_expert", 0))
			print(f"// derived_params: n_embd={n_embd} n_head={n_head} n_head_dim={n_head_dim} n_hc={n_hc} n_expert={n_expert}")
		except Exception:
			pass
	print("")
	print("#pragma once")
	print("")
	print('#include "ggml.h"')
	print('#include <string>')
	print("")
	print(f"namespace {ns} {{")
	print("")
	print(f"struct {struct_name} {{")
	for field, _ in TENSOR_BINDINGS:
		print(f"\tggml_tensor *{sanitize_ident(field)} = nullptr;")
	print("};")
	print("")
	print(f"static inline bool bind_{struct_name}({struct_name} *s, ggml_context *ctx, std::string *err) {{")
	print("\tif (s == nullptr || ctx == nullptr) {")
	print("\t\tif (err != nullptr) *err = \"null input\";")
	print("\t\treturn false;")
	print("\t}")

	for i, (field, name) in enumerate(TENSOR_BINDINGS):
		t = tmap[name]
		dims = t.get("dims", None)
		typ = t.get("type", None)
		if not isinstance(dims, list) or not all(isinstance(x, int) for x in dims):
			return die(f"tensor {name} missing dims[] list of ints")
		if not isinstance(typ, str):
			return die(f"tensor {name} missing type string")
		ggml_type = GGML_TYPE_MAP.get(typ, None)
		if ggml_type is None:
			return die(f"tensor {name} has unsupported type={typ!r}; extend GGML_TYPE_MAP if needed")

		var = f"s->{sanitize_ident(field)}"
		print("")
		print(f"\t{var} = ggml_get_tensor(ctx, \"{name}\");")
		print(f"\tif ({var} == nullptr) {{")
		print(f"\t\tif (err != nullptr) *err = \"missing tensor: {name}\";")
		print("\t\treturn false;")
		print("\t}")
		print(f"\tif ({var}->type != {ggml_type}) {{")
		print(f"\t\tif (err != nullptr) *err = \"tensor has unexpected type: {name}\";")
		print("\t\treturn false;")
		print("\t}")
		print(f"\tif (!({cxx_dims_check(var, dims)})) {{")
		print(f"\t\tif (err != nullptr) *err = \"tensor has unexpected dims: {name}\";")
		print("\t\treturn false;")
		print("\t}")

	print("")
	print("\treturn true;")
	print("}")
	print("")
	print(f"}} // namespace {ns}")
	return 0


if __name__ == "__main__":
	sys.exit(main())
