#!/usr/bin/env sh
set -eu

# vLLM target-only + optional DFlash paired probe wrapper.
# This does not fetch weights or install runtimes; it just sets a consistent low-cost run shape.

target="${1:-spark0@aitopatom-9ab9.local}"

if [ "${VLLM_TARGET_MODEL:-}" = "" ]; then
    echo "VLLM_TARGET_MODEL=/abs/path/to/target_model_dir is required" >&2
    exit 2
fi

ALLOW_RUN="${ALLOW_RUN:-1}"
ALLOW_FETCH="${ALLOW_FETCH:-0}"
PROMPT="${PROMPT:-Explain Redis streams in one paragraph.}"
MAX_TOKENS="${MAX_TOKENS:-64}"
TENSOR_PARALLEL_SIZE="${TENSOR_PARALLEL_SIZE:-1}"
VLLM_TRUST_REMOTE_CODE="${VLLM_TRUST_REMOTE_CODE:-1}"
VLLM_EXTRA_LLM_KWARGS_JSON="${VLLM_EXTRA_LLM_KWARGS_JSON:-{}}"
VLLM_EXTRA_SAMPLING_KWARGS_JSON="${VLLM_EXTRA_SAMPLING_KWARGS_JSON:-{}}"
DFLASH_NUM_SPEC_TOKENS="${DFLASH_NUM_SPEC_TOKENS:-15}"

RUN_LABEL="${RUN_LABEL:-vllm-dflash}"
MODEL_RUNS_CSV="${MODEL_RUNS_CSV:-}"
VLLM_TARGET_ID="${VLLM_TARGET_ID:-}"
VLLM_MODEL_ID="${VLLM_MODEL_ID:-}"
VLLM_SCOPE_TARGET="${VLLM_SCOPE_TARGET:-vllm_target}"
VLLM_SCOPE_DFLASH="${VLLM_SCOPE_DFLASH:-vllm_dflash}"
PUBLIC_QUALITY_PRIOR="${PUBLIC_QUALITY_PRIOR:-}"
PUBLIC_QUALITY_BASIS="${PUBLIC_QUALITY_BASIS:-}"
PUBLIC_QUALITY_SOURCE="${PUBLIC_QUALITY_SOURCE:-}"
PASSED_TASKS="${PASSED_TASKS:-}"
TOTAL_TASKS="${TOTAL_TASKS:-}"
LOCAL_QUALITY_SCORE="${LOCAL_QUALITY_SCORE:-}"
QUALITY_SCORE="${QUALITY_SCORE:-}"

sh_quote()
{
    v="${1:-}"
    printf "'%s'" "$(printf %s "$v" | sed "s/'/'\\''/g")"
}

base_env="ALLOW_RUN=$(sh_quote "$ALLOW_RUN") ALLOW_FETCH=$(sh_quote "$ALLOW_FETCH") VLLM_MODEL=$(sh_quote "$VLLM_TARGET_MODEL") PROMPT=$(sh_quote "$PROMPT") MAX_TOKENS=$(sh_quote "$MAX_TOKENS") TENSOR_PARALLEL_SIZE=$(sh_quote "$TENSOR_PARALLEL_SIZE") VLLM_TRUST_REMOTE_CODE=$(sh_quote "$VLLM_TRUST_REMOTE_CODE") VLLM_EXTRA_LLM_KWARGS_JSON=$(sh_quote "$VLLM_EXTRA_LLM_KWARGS_JSON") VLLM_EXTRA_SAMPLING_KWARGS_JSON=$(sh_quote "$VLLM_EXTRA_SAMPLING_KWARGS_JSON")"

REMOTE_LLAMA_ENV="${REMOTE_LLAMA_ENV:-ALLOW_RUN=0 ALLOW_MODEL_INSPECT=0}"
REMOTE_GGUF_INSPECT_ENV="${REMOTE_GGUF_INSPECT_ENV:-ALLOW_MODEL_INSPECT=0}"
REMOTE_MTP_SIDECAR_ENV="${REMOTE_MTP_SIDECAR_ENV:-ALLOW_RUN=0}"

vllm_model_id="$VLLM_MODEL_ID"
if [ "$vllm_model_id" = "" ]; then
    vllm_model_id="$VLLM_TARGET_ID"
fi
if [ "$vllm_model_id" = "" ]; then
    vllm_model_id="$VLLM_TARGET_MODEL"
fi

echo "== vLLM target-only =="
RUN_LABEL="$RUN_LABEL-target" VLLM_SCOPE="$VLLM_SCOPE_TARGET" MODEL_RUNS_CSV="$MODEL_RUNS_CSV" VLLM_MODEL_ID="$vllm_model_id" PUBLIC_QUALITY_PRIOR="$PUBLIC_QUALITY_PRIOR" PUBLIC_QUALITY_BASIS="$PUBLIC_QUALITY_BASIS" PUBLIC_QUALITY_SOURCE="$PUBLIC_QUALITY_SOURCE" PASSED_TASKS="$PASSED_TASKS" TOTAL_TASKS="$TOTAL_TASKS" LOCAL_QUALITY_SCORE="$LOCAL_QUALITY_SCORE" QUALITY_SCORE="$QUALITY_SCORE" REMOTE_LLAMA_ENV="$REMOTE_LLAMA_ENV" REMOTE_GGUF_INSPECT_ENV="$REMOTE_GGUF_INSPECT_ENV" REMOTE_MTP_SIDECAR_ENV="$REMOTE_MTP_SIDECAR_ENV" REMOTE_VLLM_ENV="$base_env" scripts/run_baseline_existing_runtime.sh "$target"

if [ "${VLLM_DRAFT_MODEL:-}" = "" ]; then
    echo "VLLM_DRAFT_MODEL not set; skipping DFlash run"
    exit 0
fi

spec_json="{\"method\":\"dflash\",\"model\":\"${VLLM_DRAFT_MODEL}\",\"num_speculative_tokens\":${DFLASH_NUM_SPEC_TOKENS}}"

echo
echo "== vLLM DFlash (paired) =="
dflash_env="$base_env VLLM_SPECULATIVE_CONFIG_JSON=$(sh_quote "$spec_json")"
RUN_LABEL="$RUN_LABEL-dflash" VLLM_SCOPE="$VLLM_SCOPE_DFLASH" MODEL_RUNS_CSV="$MODEL_RUNS_CSV" VLLM_MODEL_ID="$vllm_model_id" PUBLIC_QUALITY_PRIOR="$PUBLIC_QUALITY_PRIOR" PUBLIC_QUALITY_BASIS="$PUBLIC_QUALITY_BASIS" PUBLIC_QUALITY_SOURCE="$PUBLIC_QUALITY_SOURCE" PASSED_TASKS="$PASSED_TASKS" TOTAL_TASKS="$TOTAL_TASKS" LOCAL_QUALITY_SCORE="$LOCAL_QUALITY_SCORE" QUALITY_SCORE="$QUALITY_SCORE" REMOTE_LLAMA_ENV="$REMOTE_LLAMA_ENV" REMOTE_GGUF_INSPECT_ENV="$REMOTE_GGUF_INSPECT_ENV" REMOTE_MTP_SIDECAR_ENV="$REMOTE_MTP_SIDECAR_ENV" REMOTE_VLLM_ENV="$dflash_env" scripts/run_baseline_existing_runtime.sh "$target"
